:sectnums:
:toc:

= Workshop on Modeling Language Engineering (MLE) − Organisation Guide
The MLE Steering Committee


This document defines the role of the MLE Steering Committee (SC), presents to current and future Organization Committees (OCs) how the SC envisions the organization of the MLE workshop.

== Role of the Steering Committee (SC)

=== Choice of an MLE Organization Committee (OC)

Each year the SC will discuss (offline at MODELS, or online) to come up with a list of potential MLE organizers for the following year. 
The goal is to have 3 organizers in the OC, and to try to mix members from academia and from the industry.

When possible, one member of the SC will be part of the OC, both to ensure the SC point of view is well considered, and to automatically have (part of) the SC informed of the decisions made by the OC.


=== Interaction with the OC

The SC proposes a format to the OC but lets it open for discussion. 
This document aims to present the said format along with organization guidelines.

The SC should be "in-the-loop" for most decisions made by the OC. 
This means the OC should try to notify the SC for each of the main decisions (proposal/CfP content, PC, keynote speaker invitation) and main milestones (workshop proposal submission, website publication, etc.).
This allows the SC to give feedback if needed.

=== Rotation of the SC

The SC will be stable and a rotation will only occur when an SC member steps back.

== Organization of the MLE workshop

=== PC & Submissions

==== Program Committee (PC) management

The size of the PC should roughly be between 12 and 20. The list of considered researchers for the PC can be based on the PC from the previous MLE edition, but a rotation of at least 20% (hence ~5 persons) is preferable.

The OC should pay attention to diversity in the PC (industry / academia, gender, geographic area, race, research expertise, research topics, etc.).

A shared document will be made available to list all past PC members of MLE, and can be used to efficiently rotate from one edition to another. 
In particular, if former PC members were problematic (eg. very late reviews, bad reviews, bad behavior), comments should be added to this shared document to explain why such former members should not be reinvited.

==== Reviews management

The OC is free to manage reviews as they want (meta-reviews or not, discussion management, etc.). We do advise to pay attention to reviews from members of the industry which may rely on different criteria as members of academia, and to judge accordingly.

==== Types of submissions

The SC suggests to be aligned with the submission formats suggested by the host conference (eg. MODELS).

As contributions, we expect early research results on the workshop topics, descriptions of case studies, or descriptions of practical experience, opinions, and related approaches.

Papers that describe use cases, or novel approaches can be accompanied by concrete artifacts, such as models (requirements, design, analysis, transformation, composition, etc.), stored in a public repository (e.g. ReMoDD). 


We encourage "Applied Practice" papers where at least one author must be from the industry, and where reviewers should not judge the scientific novelty but should only judge whether the content is useful and relevant for the community.


//  the following types of submissions:

// * *Research papers* (up to 8 pages)
// * *Short research papers* (up to 4 pages)
// * *"Applied Practice" papers* (up to 8 pages), where at least one author must be from the industry, and where reviewers should not judge the scientific novelty but should only judge whether the content is useful and relevant for the community.



=== Workshop format

==== Program

A typical workshop program that can be followed is is:

* First session : keynote
* Main sessions : presentations (eg. each slot with 15 minutes talk + 5 minutes Q&A)
* Last session : discussion?

The goal is to encourage interactions between participants and authors as much as possible. One idea that can be experimented is to have short discussion sessions throughout the workshop schedule, for instead one after each presentation session (using the topic of the session as a discussion starter).

==== Industry presence

The SC would like to encourage as much industry presence at possible at the MLE workshop. For instance the "Applied Practice" submission type aims to be a target solely for industry members, with slightly different evaluation criteria.

To further ensure an industry presence, the OC can also directly invite 2 or 3 industry members to make presentations (or demos) without having to write actual papers.


=== Organization

==== Sharing material between editions

An MLE github organization is available here: https://github.com/mleworkshop

The goal is to share everything related to MLE, which means among other things:

* Websites,
* Proposals,
* CFPs,
* Email templates,
* Used mailing lists,
* Statistics,
* PC members data,
* This current guide.

The github organization contains al least these two repositories:

* https://github.com/mleworkshop/mle-organization which contains all past material: proposals, cfps, etc.
* https://github.com/mleworkshop/mleworkshop.github.io which contains the website.

==== Workshop proposal

The OC can freely rely on the past editions proposals and websites to assemble a workshop proposal for MODELS.

==== Milestones to consider

.January−March
* Preparation of the workshop proposal,
* Preparation of the workshop website,
* Submission of the workshop proposal (around March),

.April−June
* Workshop acceptance,
* Create EasyChair submission page,
* Make website online,
* Update Twitter account description and banner,
* PC invitation,
* Keynote invitation,
* 1st CFP sent to mailing lists,
* 2nd CFP sent to mailing lists (if possible when the keynote is known),

.July−August
* Submission deadline reached,
* Bidding,
* Assignment of papers,
* Receive all the reviews,
* Start and manage discussions,
* Decisions + notifications,
* Update workshop page with the program,

.September−October
* Workshop


=== Communication

==== Website

The MLE website is hosted as a Github page at this address: http://mleworkshop.github.io/

The base content of the website gives only very basic information, such as a list of previous MLE editions, a link to the page of the next/current edition, and the SC list.

Then each edition website is available as a single web page nested in the main website (eg. https://mleworkshop.github.io/editions/mle2020.)

The website is created using Jekyll, and can be edited using this Github repository: https://github.com/mleworkshop/mleworkshop.github.io.

==== Mailing lists

Most communication will be done using two mailing lists : one for the SC (mailto:mle-cs@inria.fr[mle-sc@inria.fr]), one for the for the OC (mle@inria.fr).

Both mailing lists are managed by the Inria SYMPA mailing list service using these pages:

* https://sympa.inria.fr/sympa/info/mle
* https://sympa.inria.fr/sympa/info/mle-sc

==== Official Twitter account

The MLE workshop series has its own official Twitter account named _@MleWorkshop_.

The OC is responsible for updating the account as required (eg. changing the banner, changing the description), and should use this account for all announcements and news about the workshop. As MLE is so far always part of MODELS, it is advised to mention the MODELS twitter account in most tweets (_@modelsconf_) and to use the official tag of the corresponding MODELS edition (eg _#models22_).

To get access to the Twitter account, the OC can simply ask the credentials to the SC.

==== Advertising the workshop

The OC is encouraged to communicate about the workshop using the official MLE Twitter account and their personal twitter accounts. 
Among other things, tweeting about the workshop acceptance, the CFPs, and the deadlines are good ideas.

In addition, the CFPs should be sent to as many mailing lists as possible. A shared document with all considered mailing lists is available in the github repository.

In addition, the SC should help the OC to communicate about the workshop. This requires the OC to keep the SC in the loop when sending CFPs.
